name: flappy_bird_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.23.0
  logging: ^1.3.0
  flame_audio: ^2.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: flappy
      fonts:
      - asset: assets/fonts/flappy.ttf
    - family: robot
      fonts:
      - asset: assets/fonts/font.ttf
#      style: italic
#    - family: Trajan Pro
#      fonts:
#         - asset: assets/fonts/TrajanPro.ttf
#         - asset: assets/fonts/TrajanPro_Bold.ttf
#           weight: 700
