# Generated by Django 5.1.6 on 2025-02-22 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='full_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.timeslot'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.product'),
        ),
    ]
